config/routes.rb
Rails.application.routes.draw do
  resources :cliente_elites
  resources :socios
  resources :banco
  resources :dashboard
  resources :compras_personales
  resources :estado_cuenta
  resources :plan_de_negocios
  resources :facturas
  resources :proveedors
  resources :precios
  resources :conceptos
  resources :pagos
  resources :asentamientos
  resources :paises
  resources :estados  
  resources :ciudads
  resources :categories
  root to: 'dashboard#index'
  post '/categories/search'
  post '/socios/search'
  post '/cliente_elites/search'
  post '/paises/search'

  devise_for :usuarios
  scope '/admin' do
    resources :usuarios
    post '/usuarios/search'
    resources :permisos
    resources :roles
  end
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
	belongs_to :role, :class_name => "Role", :foreign_key => "role_id"

	def mensaje
		{0 => {true => "Ver listado", false => ""}, 1 => {true => "Ver elemento", false => ""},
		2 => {true => "Crear nuevo", false => ""}, 3 => {true => "Editar", false => ""},
		4 => {true => "Eliminar", false => ""}, 5 => {true => "Imprimir", false => ""},
		6 => {true => "Exportar", false => ""}}
	end

	def can_do
		str = ""
		str += "<li>#{mensaje[0][can_see_index||false] || ''}</li>" if can_see_index
		str += "<li>#{mensaje[1][can_show||false] || ''}</li>" if can_show
		str += "<li>#{mensaje[2][can_create_new||false] || ''}</li>" if can_create_new
		str += "<li>#{mensaje[3][can_edit||false] || ''}</li>" if can_edit
		str += "<li>#{mensaje[4][can_delete||false] || ''}</li>" if can_delete
		str += "<li>#{mensaje[5][can_print||false] || ''}</li>" if can_print
		str += "<li>#{mensaje[6][can_export||false] || ''}</li>" if can_export
		str
	end

	def to_s
		"<span>En #{descripcion} puede: <ul>#{can_do}</ul></span><br>"
	end
end

app/controllers/permisos_controller.rb
class PermisosController < ApplicationController
  before_action :set_permiso, only: [:show, :edit, :update, :destroy]

  # GET /permisos
  # GET /permisos.json
  def index
    @permisos = Permiso.all
  end

  # GET /permisos/1
  # GET /permisos/1.json
  def show
  end

  # GET /permisos/new
  def new
    @permiso = Permiso.new
  end

  # GET /permisos/1/edit
  def edit
  end

  # POST /permisos
  # POST /permisos.json
  def create
    @permiso = Permiso.new(permiso_params)

    respond_to do |format|
      if @permiso.save
        format.html { redirect_to @permiso, notice: 'Permiso was successfully created.' }
        format.json { render :show, status: :created, location: @permiso }
      else
        format.html { render :new }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisos/1
  # PATCH/PUT /permisos/1.json
  def update
    respond_to do |format|
      if @permiso.update(permiso_params)
        format.html { redirect_to @permiso, notice: 'Permiso was successfully updated.' }
        format.json { render :show, status: :ok, location: @permiso }
      else
        format.html { render :edit }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisos/1
  # DELETE /permisos/1.json
  def destroy
    @permiso.destroy
    respond_to do |format|
      format.html { redirect_to permisos_url, notice: 'Permiso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso
      @permiso = Permiso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_params
      params.require(:permiso).permit(:descripcion, :can_see_index, :can_show, :can_create_new, :can_edit, :can_delete, :can_print, :can_export)
    end
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/views/permisos/_form.html.erb
<%= form_for(@permiso) do |f| %>
  <% if @permiso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permiso.errors.count, "error") %> prohibited this permiso from being saved:</h2>

      <ul>
      <% @permiso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :can_see_index %><br>
    <%= f.check_box :can_see_index %>
  </div>
  <div class="field">
    <%= f.label :can_show %><br>
    <%= f.check_box :can_show %>
  </div>
  <div class="field">
    <%= f.label :can_create_new %><br>
    <%= f.check_box :can_create_new %>
  </div>
  <div class="field">
    <%= f.label :can_edit %><br>
    <%= f.check_box :can_edit %>
  </div>
  <div class="field">
    <%= f.label :can_delete %><br>
    <%= f.check_box :can_delete %>
  </div>
  <div class="field">
    <%= f.label :can_print %><br>
    <%= f.check_box :can_print %>
  </div>
  <div class="field">
    <%= f.label :can_export %><br>
    <%= f.check_box :can_export %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permisos/edit.html.erb
<h1>Editing Permiso</h1>

<%= render 'form' %>

<%= link_to 'Show', @permiso %> |
<%= link_to 'Back', permisos_path %>

app/views/permisos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Permisos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Tipo accion</th>
      <th>Parent</th>
      <th>Treepath</th>
      <th>Node level</th>
      <th>Has child</th>
      <th>Iorder</th>
      <th>Object</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permisos.each do |permiso| %>
      <tr>
        <td><%= permiso.descripcion %></td>
        <td><%= permiso.can_see_index %></td>
        <td><%= permiso.can_show %></td>
        <td><%= permiso.can_create_new %></td>
        <td><%= permiso.can_edit %></td>
        <td><%= permiso.can_delete %></td>
        <td><%= permiso.can_print %></td>
        <td><%= permiso.can_export %></td>
        <td><%= link_to 'Show', permiso %></td>
        <td><%= link_to 'Edit', edit_permiso_path(permiso) %></td>
        <td><%= link_to 'Destroy', permiso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permiso', new_permiso_path %>

app/views/permisos/new.html.erb
<h1>New Permiso</h1>

<%= render 'form' %>

<%= link_to 'Back', permisos_path %>

app/views/permisos/show.html.erb
<p id="notice"><%= notice %></p>


<%= render "form" %>

<%= link_to 'Edit', edit_permiso_path(@permiso) %> |
<%= link_to 'Back', permisos_path %>