config/routes.rb
Rails.application.routes.draw do
  resources :cliente_elites
  resources :socios
  resources :banco
  resources :dashboard
  resources :compras_personales
  resources :estado_cuenta
  resources :plan_de_negocios
  resources :facturas
  resources :proveedors
  resources :precios
  resources :conceptos
  resources :pagos
  resources :asentamientos
  resources :paises
  resources :estados  
  resources :ciudads
  resources :categories
  root to: 'dashboard#index'
  post '/categories/search'
  post '/socios/search'
  post '/cliente_elites/search'
  post '/paises/search'

  devise_for :usuarios
  scope '/admin' do
    resources :usuarios
    post '/usuarios/search'
    resources :permisos
    resources :roles
  end
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_many :ciudads, class_name: 'Ciudad', foreign_key: 'estado_id'
  belongs_to :pais, class_name: 'Paise', foreign_key: 'pais_id'

  validates_presence_of :estado, on: :create, message: 'no puede ser blanco'
  validates_presence_of :clave, on: :create, message: 'no puede ser blanco'
  validates_presence_of :pais_id, on: :create, message: 'es obligatorio'


  def to_s
  	clave
  end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:estado, :clave, :pais_id)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<div class="panel-body">
  <%= form_for(@estado, html: {class: "new_estado form-default"}) do |f| %>
    <% if @estado.errors.any? %>
      <%= error_explanation_dialog @estado %>
    <% end %>

    <div class="form-group">
      <%= f.label :estado %>
      <%= f.text_field :estado, class: "form-control col-lg-2" %>
    </div>
    <div class="form-group">
      <%= f.label :clave %>
      <%= f.text_field :clave, class: "form-control col-lg-2" %>
    </div>
    <div class="form-group">
      <%= f.label :pais_id %>
      <%= f.collection_select :pais_id, Paise.all, :id, :pais, {prompt: true}, {class: "form-control"} %>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
      <%= f.submit "Guardar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/estados/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Estado</h3>
  </div>

	<%= render 'form' %>

</div>

<%= link_to 'Ver', @estado, class: "btn btn-primary" %> |
<%= link_to 'Volver', estados_path, class: "btn btn-info" %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
  <caption><h1>Estados</h1></caption>
  <table class="table table-striped table-hover">
    <thead>
      <tr class="info">
        <th>Estado</th>
        <th>Clave</th>
        <th>Pais</th>
        <th colspan="3">Acción</th>
      </tr>
    </thead>

    <tbody>
      <% @estados.each do |estado| %>
        <tr>
          <td><%= estado.estado %></td>
          <td><%= estado.clave %></td>
          <td><%= estado.pais.pais if estado.pais %></td>
          <td><%= link_to 'Ver', estado, class: "btn btn-primary btn-xs" %></td>
          <td><%= link_to 'Edit', edit_estado_path(estado), class: "btn btn-info btn-xs" %></td>
          <td><%= link_to 'Eliminar', estado, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Nuevo Estado', new_estado_path, class: "btn btn-success" %>

app/views/estados/new.html.erb
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <h3 class='panel-title'>Nuevo Estado</h3>
  </div>

  <%= render 'form' %>

</div>

<%= link_to 'Volver', estados_path, class: 'btn btn-primary' %>

app/views/estados/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Ver Estado</h3>
  </div>
  <div class="panel-body">
		<p>
		  <strong>Estado:</strong>
		  <%= @estado.estado %>
		</p>

		<p>
		  <strong>Clave:</strong>
		  <%= @estado.clave %>
		</p>

		<p>
		  <strong>Pais:</strong>
		  <%= @estado.pais_id %>
		</p>

	</div>
</div>

<%= link_to 'Editar', edit_estado_path(@estado), class: "btn btn-primary" %> |
<%= link_to 'Volver', estados_path, class: "btn btn-info" %>