config/routes.rb
Rails.application.routes.draw do
  resources :cliente_elites
  resources :socios
  resources :banco
  resources :dashboard
  resources :compras_personales
  resources :estado_cuenta
  resources :plan_de_negocios
  resources :facturas
  resources :proveedors
  resources :precios
  resources :conceptos
  resources :pagos
  resources :asentamientos
  resources :paises
  resources :estados  
  resources :ciudads
  resources :categories
  root to: 'dashboard#index'
  post '/categories/search'
  post '/socios/search'
  post '/cliente_elites/search'
  post '/paises/search'

  devise_for :usuarios
  scope '/admin' do
    resources :usuarios
    post '/usuarios/search'
    resources :permisos
    resources :roles
  end
end

app/models/precio.rb
class Precio < ActiveRecord::Base
  belongs_to :category
  belongs_to :concepto
  belongs_to :usuario
end

app/controllers/precios_controller.rb
class PreciosController < ApplicationController
  before_action :set_precio, only: [:show, :edit, :update, :destroy]

  # GET /precios
  # GET /precios.json
  def index
    @precios = Precio.all
  end

  # GET /precios/1
  # GET /precios/1.json
  def show
  end

  # GET /precios/new
  def new
    @precio = Precio.new
  end

  # GET /precios/1/edit
  def edit
  end

  # POST /precios
  # POST /precios.json
  def create
    @precio = Precio.new(precio_params)

    respond_to do |format|
      if @precio.save
        format.html { redirect_to @precio, notice: 'Precio was successfully created.' }
        format.json { render :show, status: :created, location: @precio }
      else
        format.html { render :new }
        format.json { render json: @precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precios/1
  # PATCH/PUT /precios/1.json
  def update
    respond_to do |format|
      if @precio.update(precio_params)
        format.html { redirect_to @precio, notice: 'Precio was successfully updated.' }
        format.json { render :show, status: :ok, location: @precio }
      else
        format.html { render :edit }
        format.json { render json: @precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precios/1
  # DELETE /precios/1.json
  def destroy
    @precio.destroy
    respond_to do |format|
      format.html { redirect_to precios_url, notice: 'Precio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precio
      @precio = Precio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precio_params
      params.require(:precio).permit(:fecha, :category_id, :concepto_id, :precio_normal, :precio_pronto_pago, :fecha_pronto_pago, :vigencia_de, :vigencia_hasta, :activo, :usuario_id)
    end
end

app/helpers/precios_helper.rb
module PreciosHelper
end

app/views/precios/_form.html.erb
<%= form_for(@precio) do |f| %>
  <% if @precio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@precio.errors.count, "error") %> prohibited this precio from being saved:</h2>

      <ul>
      <% @precio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.collection_select :category_id, Category.where(parent_id: 213), :id, :categoria %>
  </div>
  <div class="field">
    <%= f.label :concepto_id %><br>
    <%= f.collection_select :concepto_id, Concepto.all, :id, :concepto, {prompt: true} %>
  </div>
  <div class="field">
    <%= f.label :precio_normal %><br>
    <%= f.text_field :precio_normal %>
  </div>
  <div class="field">
    <%= f.label :precio_pronto_pago %><br>
    <%= f.text_field :precio_pronto_pago %>
  </div>
  <div class="field">
    <%= f.label :fecha_pronto_pago %><br>
    <%= f.date_select :fecha_pronto_pago %>
  </div>
  <div class="field">
    <%= f.label :vigencia_de %><br>
    <%= f.date_select :vigencia_de %>
  </div>
  <div class="field">
    <%= f.label :vigencia_hasta %><br>
    <%= f.date_select :vigencia_hasta %>
  </div>
  <div class="field">
    <%= f.label :activo %><br>
    <%= f.check_box :activo %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= text_field_tag 'pago[usuario_id]', current_usuario.id, options={readonly: true} %> <%= current_usuario.usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/precios/edit.html.erb
<h1>Editing Precio</h1>

<%= render 'form' %>

<%= link_to 'Show', @precio %> |
<%= link_to 'Back', precios_path %>

app/views/precios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Precios</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Category</th>
      <th>Concepto</th>
      <th>Precio normal</th>
      <th>Precio pronto pago</th>
      <th>Fecha pronto pago</th>
      <th>Vigencia de</th>
      <th>Vigencia hasta</th>
      <th>Activo</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @precios.each do |precio| %>
      <tr>
        <td><%= precio.fecha %></td>
        <td><%= precio.category %></td>
        <td><%= precio.concepto %></td>
        <td><%= precio.precio_normal %></td>
        <td><%= precio.precio_pronto_pago %></td>
        <td><%= precio.fecha_pronto_pago %></td>
        <td><%= precio.vigencia_de %></td>
        <td><%= precio.vigencia_hasta %></td>
        <td><%= precio.activo %></td>
        <td><%= precio.usuario %></td>
        <td><%= link_to 'Show', precio %></td>
        <td><%= link_to 'Edit', edit_precio_path(precio) %></td>
        <td><%= link_to 'Destroy', precio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Precio', new_precio_path %>

app/views/precios/new.html.erb
<h1>New Precio</h1>

<%= render 'form' %>

<%= link_to 'Back', precios_path %>

app/views/precios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @precio.fecha %>
</p>

<p>
  <strong>Category:</strong>
  <%= @precio.category %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @precio.concepto %>
</p>

<p>
  <strong>Precio normal:</strong>
  <%= @precio.precio_normal %>
</p>

<p>
  <strong>Precio pronto pago:</strong>
  <%= @precio.precio_pronto_pago %>
</p>

<p>
  <strong>Fecha pronto pago:</strong>
  <%= @precio.fecha_pronto_pago %>
</p>

<p>
  <strong>Vigencia de:</strong>
  <%= @precio.vigencia_de %>
</p>

<p>
  <strong>Vigencia hasta:</strong>
  <%= @precio.vigencia_hasta %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @precio.activo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @precio.usuario %>
</p>

<%= link_to 'Edit', edit_precio_path(@precio) %> |
<%= link_to 'Back', precios_path %>